# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [ ]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

In [ ]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

In [ ]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


In [ ]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

In [ ]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

In [ ]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

In [ ]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

In [ ]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

In [ ]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

In [ ]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

In [ ]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

In [ ]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

In [ ]:
# break here for next video!

In [ ]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

In [ ]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

In [ ]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

In [ ]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


In [ ]:
print(rand_mat[0:2,1:3])

In [ ]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

In [ ]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

In [ ]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


In [ ]:
print(rand_mat)

In [ ]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


In [ ]:
# break here for next video

In [ ]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

In [ ]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

In [ ]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

In [ ]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [ ]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [ ]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

In [ ]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

In [ ]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

In [2]:
import pandas as pd

In [16]:
demo_array = np.arange(10,17)
demo_array [:]= 101
demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [15]:
a = [12,34,55]
np.array(a)

array([12, 34, 55])

In [8]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [9]:
data = {'prodID': ['101', '102', '103', '104', '104'],

                    'prodname': ['X', 'Y', 'Z', 'X', 'W'],

                     'profit': ['2738', '2727', '3497', '7347', '3743']}

In [10]:
dataframe = pd.DataFrame(data)
dataframe

prodID prodname profit
0    101        X   2738
1    102        Y   2727
2    103        Z   3497
3    104        X   7347
4    104        W   3743

In [11]:
grouped_data = dataframe.groupby('prodID')
grouped_data.max()

prodname profit
prodID                
101           X   2738
102           Y   2727
103           Z   3497
104           X   7347

In [18]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[2,3]

39

In [13]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38], [73,39,93,39]))
demo_matrix[:, (1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [17]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])

flowers['daisy']

5

In [19]:
s1 = pd.Series(['a', 'b'])
s1

0    a
1    b
dtype: object

In [20]:
s2 = pd.Series(['c', 'd'])
s2

0    c
1    d
dtype: object

In [25]:
pd.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: object

In [26]:
score = [10, 15, 20, 25]

pd.Series(data=score, index = ['a','b','c','d'])

a    10
b    15
c    20
d    25
dtype: int64

In [27]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [28]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38], [73,39,93,39]))

demo_matrix[:, (1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [29]:
demo_array = np.arange(10,17)

demo_array [:]= 101

demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [30]:
data = {'prodID': ['101', '102', '103', '104', '104'],

                    'prodname': ['X', 'Y', 'Z', 'X', 'W'],

                     'profit': ['2738', '2727', '3497', '7347', '3743']}

dataframe = pd.DataFrame(data)

dataframe

prodID prodname profit
0    101        X   2738
1    102        Y   2727
2    103        Z   3497
3    104        X   7347
4    104        W   3743

In [31]:
grouped_data = dataframe.groupby('prodID')

grouped_data.max()

prodname profit
prodID                
101           X   2738
102           Y   2727
103           Z   3497
104           X   7347